name:                 rca
version:              0.1.0.0
visibility:           public
id:                   rca-0.1.0.0-inplace
key:                  rca-0.1.0.0-inplace
author:               Gavin Walters
synopsis:             Regulated Cell Architecture - Haskell Variant
abi:                  inplace
exposed:              True
exposed-modules:      RCA.Cell RCA.Control RCA.Data RCA.Engine RCA.Thread
import-dirs:
    /home/gwalters/Workspace/regulated-cell-architecture/variants/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rca-0.1.0.0/build

library-dirs:
    /home/gwalters/Workspace/regulated-cell-architecture/variants/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rca-0.1.0.0/build

library-dirs-static:
    /home/gwalters/Workspace/regulated-cell-architecture/variants/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rca-0.1.0.0/build

dynamic-library-dirs:
    /home/gwalters/Workspace/regulated-cell-architecture/variants/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rca-0.1.0.0/build

data-dir:
    /home/gwalters/Workspace/regulated-cell-architecture/variants/haskell/.

hs-libraries:         HSrca-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    /home/gwalters/Workspace/regulated-cell-architecture/variants/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rca-0.1.0.0/doc/html/rca/rca.haddock

haddock-html:
    /home/gwalters/Workspace/regulated-cell-architecture/variants/haskell/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rca-0.1.0.0/doc/html/rca
